### ISSUE TITLE
Crash upon importing 24 word key using init

### ISSUE THREAD

**Issue by unclemantis** [syvita/storm#3]
npm-global\5\node_modules\.pnpm\@syvita+storm@0.4.0\node_modules\@syvita\storm\build\index.js:263
))}else{let{key:i,password:o}=await(0,uw.default)([{type:"text",name:"key",message:"Enter your Secret Key",validate:a=>Fle.default.validateMnemonic(a)?!0:"Invalid Secret Key"},{type:"password",name:"password",message:"Enter a password",validate:a=>a.length<6?"Password must be at least 6 characters":!0}]);du();let s=Hn("Importing Secret Key").start();await jk(i,o),s.succeed("Imported Secret Key"),du(iy.default.green(
                                                                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'validateMnemonic')
    at O$.validate [as validator] (C:\Users\Michael\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@syvita+storm@0.4.0\node_modules\@syvita\storm\build\index.js:263:133)
    at O$.validate (C:\Users\Michael\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@syvita+storm@0.4.0\node_modules\@syvita\storm\build\index.js:80:51)
    at O$.submit (C:\Users\Michael\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@syvita+storm@0.4.0\node_modules\@syvita\storm\build\index.js:80:248)
    at ReadStream.i (C:\Users\Michael\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@syvita+storm@0.4.0\node_modules\@syvita\storm\build\index.js:79:936)
    at ReadStream.emit (node:events:390:28)
    at emitKeys (node:internal/readline/utils:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:61:36)
    at ReadStream.emit (node:events:402:35)
    at addChunk (node:internal/streams/readable:315:12)
PS C:\Users\Michael\documents>

**Comment by 0xAsteria** [comment]
Resolved in 5cce9ee106737c24ee29e1bb583d9385fe16b82c.
